plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num/"
permalink: "/:year/:month/:title"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Abwao"
      style: "post.css"