plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 7
paginate_path: "/blog/page:num/"
permalink: "/:year/:month/:title"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Abwao"
      style: "post.css"

# For SEO
logo: /assets/images/logo.png
social:
  name: Timothy Abwao
  links:
    - https://ke.linkedin.com/in/timothy-abwao
    - https://github.com/Tim-Abwao
    - https://twitter.com/timoam
    - https://www.kaggle.com/timothyabwao
    - https://www.hackerrank.com/abwaomusungu
twitter:
  username: TimoAM
  card: summary
